//
// Created by skd on 06.03.2025.
//

#ifndef GCODE_REDUCED_COMMANDS_H
#define GCODE_REDUCED_COMMANDS_H

enum GCode : uint8_t {
    GCODE_MOVE = 10,
    GCODE_HOME = 20,
    GCODE_SET_OFFSET = 30,
    GCODE_SET_HOME_SPEED_COARSE = 40,
    GCODE_SET_HOME_SPEED_FINE = 50,
    GCODE_STOP = 60,
    GCODE_DISABLE_MOTOR = 70,
    GCODE_ENABLE_MOTOR = 80,
    GCODE_WAIT = 90
};
#endif //GCODE_REDUCED_COMMANDS_H
